### ISSUE TITLE
Accessing network shares on windows: FileNotFoundException

### ISSUE THREAD

**Issue by tpietzsch** [PreibischLab/multiview-reconstruction#14]
When trying to save a xml file that was loaded from a network share, like `\\Hive3000\dataset_loci.xml`, a `java.io.FileNotFoundException` is caused.
This is because here
https://github.com/PreibischLab/multiview-reconstruction/blob/426b51812633051e8c0e4634d420f4d2925eb4e0/src/main/java/net/preibisch/mvrecon/fiji/spimdata/explorer/FilteredAndGroupedExplorerPanel.java#L111
the `\\Hive3000\dataset_loci.xml` is translated to `/Hive3000/dataset_loci.xml`.
I.e., double `\\` is replaced by single `/`.

**Comment by StephanPreibisch** [comment]
A quick fix for windows would be to mount the share as a drive letter ... but we should fix that anyhow @hoerldavid

**Comment by StephanPreibisch** [comment]
thanks @tpietzsch

**Comment by tpietzsch** [comment]
> A quick fix for windows would be to mount the share as a drive letter ...

Jup, that's what we're doing :-)

**Comment by hoerldavid** [comment]
Hi @tpietzsch, @StephanPreibisch,

Since this issue already came up a second time (https://github.com/PreibischLab/BigStitcher/issues/29) I had a quick look and it seems that both

```java
this.xml = xml == null ? "" : xml.replace("\\\\", "////").replace( "\\", "/" ).replace( "//", "/" ).replace( "/./", "/" );
```
and
```java
this.xml = xml == null ? "" : xml;
```
work without problems, both on Windows and macOS.

* The second solution would keep displaying a potentially unnormalized path in the main window 
* while the first seems a bit unelegant (and I'm not sure if it catches every edge-case).

Originally, the replaces were introduced in 06663aa5e, do you remember any reason for doing so (aside from aesthetic reasons) @StephanPreibisch?

Cheers,
David

**Comment by hoerldavid** [comment]
I fixed it in https://github.com/PreibischLab/multiview-reconstruction/commit/688df4ea4427899abe6136457e58250846154832.

I used the first solution (add another replace), but also added the second version (no normalization) as a comment.
