### ISSUE TITLE
Optimization II does not provide speedUp

### ISSUE THREAD

**Issue by Xqua** [PreibischLab/multiview-reconstruction#19]
Hi 
I was reading the paper on the deconvolution algorithm. In it the different Benchmark show that Optimization II provides a significant speedup on iteration times. However when I try it on a dataset with 6 views I see that it takes ~10 more seconds per iteration compared to optimization I. 

Any idea why ?

**Comment by StephanPreibisch** [comment]
Hi, that speed different should just an artifact of running it at different times, it should be identical. The speed-up comes from the fact that you need less iterations to achieve a similar resolution (e.g. 10 instead of 20 iterations). It is described in great detail in the paper and the supplement: 
https://www.nature.com/articles/nmeth.2929

Best, Stephan
