### ISSUE TITLE
Very confused about the new "tiles

### ISSUE THREAD

**Issue by Xqua** [PreibischLab/multiview-reconstruction#9]

**Comment by hoerldavid** [comment]
Hi @Xqua,

The TIles are a part of the newer versions of the Multiview-Reconstruction that are installed together with its sister plugin **BigStitcher**.

Since this overlaps with the other issue you opened (https://github.com/PreibischLab/multiview-reconstruction/issues/10) I'll explain this there and close this one.

Best,
David
